feat: expose animation function to customize animation
kadiryazici/bottom-sheet-vue3 pull request #9
Opened 2023-01-24 16:17 UTC by hasanparasteh

Closes: #8 

I created a feature to manually pass a function to sheet component for handling enter & leave animation! if there was no prop it uses the default animation behavior so it's fully compatible with previous version.

I'd be happy if you review my codes and merge this PR

2023-01-25 09:31 UTC, kadiryazici requested changes

2023-01-25 09:31 UTC, kadiryazici commented on src/Component.tsx
> +          }
Firstly thanks for the PR, We should treat null and undefined differently for this behavior.

If user passes null: no transition
If user passes undefined: use default transition callback
If user passes a function: use that function as a transition callback.

And I prefer ternary operators in new line :)

```suggestion
          onEnter={
            props.handleAnimationEnter === null
              ? undefined
               : props.handleAnimationEnter || handleAnimationEnter
          }
          onLeave={
            props.handleAnimationLeave === null
              ? undefined :
              props.handleAnimationLeave || handleAnimationLeave
          }
```

2023-01-25 09:31 UTC, kadiryazici commented on src/constants.ts
> +} as const
```suggestion
const ANIMATION_CALLBACK = {
  type: Function as PropType<((element: Element, done: () => void) => void) | null | undefined>,
  default: undefined
} as const
```

2023-01-25 09:32 UTC, kadiryazici commented
And prop names should be `animationLeaveHandler` and `animationEnterHandler` because it looks like a function name.

2023-01-25 09:33 UTC, kadiryazici requested changes

2023-01-25 09:33 UTC, kadiryazici commented on src/constants.ts
> +  handleAnimationLeave: ANIMATION_CALLBACK
We should allow users to write it like `@transitionEnter` and `@transitionLeave`, vue do not care about if it is prop or an emit if it is prefixed as `on`.

```suggestion
  onTransitionEnter: TRANSITION_CALLBACK,
  onTransitionEnter: TRANSITION_CALLBACK
```

2023-01-25 14:29 UTC, kadiryazici requested changes

2023-01-25 14:29 UTC, kadiryazici commented on src/Component.tsx
> +          }
```suggestion
            props.handleAnimationEnter === null
              ? undefined
              : props.handleAnimationEnter || handleAnimationEnter
          }
          onLeave={
            props.handleAnimationLeave === null
              ? undefined
              : props.handleAnimationLeave || handleAnimationLeave
          }
```

2023-01-25 17:31 UTC, kadiryazici commented on src/Component.tsx
> +          }
you shouldn't commit my suggestions directly :) these are still staying as props.handleAnimation(start/leave)

2023-01-25 17:31 UTC, kadiryazici commented
I'm wondering why `type-check` workflow doesn't run 🤔

2023-01-25 17:55 UTC, kadiryazici commented
@hasanparasteh can you pull the latest changes? I updated workflows.

2023-01-31 12:35 UTC, hasanparasteh commented
I'll close this PR and try to remove additional and extra commits to make a clean PR.

2023-01-31 12:35 UTC, closed without merging

2023-01-31 12:40 UTC, kadiryazici commented
@hasanparasteh No need to create another PR, you just can update this one.